@echo off
rem Environment for all source-deployment subprocesses; only writes inside this workspace.
set "TEMP=D:\CodexData\tmp"
set "TMP=D:\CodexData\tmp"
set "TEMP=%~dp0.runtime\tmp"
set "TMP=%TEMP%"
set "TMPDIR=%TEMP%"
set "HOME=%~dp0.runtime\home"
set "USERPROFILE=%HOME%"
set "APPDATA=%~dp0.runtime\appdata"
set "LOCALAPPDATA=%~dp0.runtime\localappdata"
set "XDG_CACHE_HOME=%~dp0.cache"
set "XDG_CONFIG_HOME=%~dp0.runtime\config"
set "XDG_DATA_HOME=%~dp0data"
set "PIP_CACHE_DIR=%~dp0.cache\pip"
set "PIP_CONFIG_FILE=NUL"
set "PIP_DISABLE_PIP_VERSION_CHECK=1"
set "UV_CACHE_DIR=%~dp0.cache\uv"
set "PUB_CACHE=%~dp0.cache\pub"
set "PYTHONPYCACHEPREFIX=%~dp0.cache\pycache"
set "PYTHONNOUSERSITE=1"
set "FLET_APP_STORAGE_DATA=%~dp0data"
set "FLET_APP_STORAGE_CACHE=%~dp0.cache\flet"
set "FLET_APP_STORAGE_TEMP=%TEMP%"
set "ENTP_MARKDOWN_EDITOR=plain"
set "ENTP_WORKSPACE_LOCAL=1"
if not exist "%TEMP%" mkdir "%TEMP%"
if not exist "%~dp0data\backups" mkdir "%~dp0data\backups"
exit /b 0
